projects:
  neutrifyAPI:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/services/neutrify.service.ts
        docsFilePath: src/graphql
        maxDepth: 7
extensions:
  amplify:
    version: 3
