projects:
  neutrifyAPI:
    schemaPath: amplify/backend/api/neutrifyAPI/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/services/neutrify-api.service.ts
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: null
extensions:
  amplify:
    version: 3
